version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: docker/frontend/Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - backend
      - python
    networks:
      - ml-workflow

  backend:
    build:
      context: docker/backend
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    environment:
      - DATA_PATH=/data/data.json
    volumes:
      # Monta la cartella OneDrive locale per il file JSON
      # Modifica questo percorso con la tua cartella OneDrive
      - ./data:/data
    networks:
      - ml-workflow

  python:
    build:
      context: docker/ce_python
      dockerfile: Dockerfile
    ports:
      - "3002:3002"
    environment:
      - TEST_SUITE_DATA_PATH=/data/TEST_SUITE
      - AZURE_BATCH_VM_PATH=C:\Users\kq5simmarine\AppData\Local\Categorization.Classifier.NoJWT\Utils\Categorization.Classifier.Batch.AzureDataScience
      - CERT_THUMBPRINT=D0E4EB9FB0506DEF78ECF1283319760E980C1736
      - APP_ID=5fd0a365-b1c7-48c4-ba16-bdc211ddad84
    volumes:
      # Mount the TEST_SUITE data folder
      - ./data/TEST_SUITE:/data/TEST_SUITE
      # Mount the CategorizationEnginePython code
      - ./docker/ce_python/CategorizationEnginePython:/app/CategorizationEnginePython
    networks:
      - ml-workflow

networks:
  ml-workflow:
    driver: bridge
